### ISSUE TITLE
在使用github action构建gh-pages时出错

### ISSUE THREAD

**Issue by NKDark** [YunYouJun/valaxy#122]
使用valaxy模板创建

version: 
  "valaxy": "0.11.1"

只有一处修改
https://github.com/NKDark/blog/blob/main/valaxy.config.ts#L131

github action:
https://github.com/NKDark/blog/actions/runs/3434829624/jobs/5726517602

```shell
# preview
[vite-ssg] Build for client...
vite v2.9.15 building for production...
transforming...
✓ 5 modules transformed.
[vite:resolve] Missing "./preload-helper" export in "vite" package
Error:  [vite-ssg] An internal error occurred.
Error: Missing "./preload-helper" export in "vite" package
    at bail (/home/runner/work/blog/blog/node_modules/vite/dist/node/chunks/dep-6894[25](https://github.com/NKDark/blog/actions/runs/3434829624/jobs/5726517602#step:5:26)f3.js:38597:8)
    at resolve (/home/runner/work/blog/blog/node_modules/vite/dist/node/chunks/dep-689425f3.js:38674:10)
    at resolveExports (/home/runner/work/blog/blog/node_modules/vite/dist/node/chunks/dep-689425f3.js:40982:12)
    at resolveDeepImport (/home/runner/work/blog/blog/node_modules/vite/dist/node/chunks/dep-689425f3.js:41000:31)
    at tryNodeResolve (/home/runner/work/blog/blog/node_modules/vite/dist/node/chunks/dep-689425f3.js:40773:20)
    at Object.resolveId (/home/runner/work/blog/blog/node_modules/vite/dist/node/chunks/dep-689425f3.js:40581:28)
    at /home/runner/work/blog/blog/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:228[26](https://github.com/NKDark/blog/actions/runs/3434829624/jobs/5726517602#step:5:27):[37](https://github.com/NKDark/blog/actions/runs/3434829624/jobs/5726517602#step:5:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:resolve',
  hook: 'resolveId',
  watchFiles: [
    ...
  ]
}
```

**Comment by NKDark** [comment]
把.github/workflows/gh-pages.yml
修改用yarn就行了
```yaml
      - name: 📦 Install Dependencies
        run: yarn

      - name: 🌌 Build Valaxy Blog
        run: yarn build
```

**Comment by YunYouJun** [comment]
不应当……

**Comment by YunYouJun** [comment]
我的 [yunyoujun.github.io](https://github.com/YunYouJun/yunyoujun.github.io) 可正常构建。

**Comment by NKDark** [comment]
> 我的 [yunyoujun.github.io](https://github.com/YunYouJun/yunyoujun.github.io) 可正常构建。

不清楚鸭 我通过自己搭建的 ci 服务 通过 docker node:lts-alpine 镜像构建也出错
尝试本地 ci 中使用 yarn 就可以正常构建了
后面又用github action 使用 yarn 构建也是正常
也不清楚为啥
