### ISSUE TITLE
【Bug】今天更新项目依赖后出现编译错误，回退依赖版本无错误

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#312]
### Describe the bug

[05:01:56.595] [vite-ssg] Rendering Pages... (43)
[05:01:56.615] [vite-ssg] Critical CSS generation enabled via `critters`
[05:01:58.046] file:///vercel/path0/node_modules/.pnpm/vite-ssg@0.23.5_critters@0.0.20_vite@5.0.10_vue-router@4.2.5_vue@3.4.0/node_modules/vite-ssg/dist/node.mjs:1076
[05:01:58.047]         throw new Error(`${gray("[vite-ssg]")} ${red(`Error on page: ${cyan(route)}`)}
[05:01:58.047]               ^
[05:01:58.047] 
[05:01:58.047] Error: [vite-ssg] Error on page: /tags
[05:01:58.048] RangeError: Maximum call stack size exceeded
[05:01:58.048]     at Function.defineProperty (<anonymous>)
[05:01:58.048]     at Object.def (/vercel/path0/node_modules/.pnpm/@vue+shared@3.4.0/node_modules/@vue/shared/dist/shared.cjs.js:82:10)
[05:01:58.051]     at Object.markRaw (/vercel/path0/node_modules/.pnpm/@vue+reactivity@3.4.0/node_modules/@vue/reactivity/dist/reactivity.cjs.js:973:10)
[05:01:58.052]     at setupStatefulComponent (/vercel/path0/node_modules/.pnpm/@vue+runtime-core@3.4.0/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7489:31)
[05:01:58.052]     at setupComponent (/vercel/path0/node_modules/.pnpm/@vue+runtime-core@3.4.0/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7459:36)
[05:01:58.055]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:354:15)
[05:01:58.056]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.056]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.056]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.056]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.056]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.056]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.056]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.056]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.056]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.056]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.056]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.056]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.057]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.057]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.057]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.057]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.057]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.057]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.057]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.057]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.057]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.057]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.057]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.057]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.058]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.058]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.058]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.058]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.058]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.058]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.058]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.058]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.058]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.058]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.058]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.058]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.058]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.059]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.059]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.059]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.059]     at ssrRenderComponent (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)
[05:01:58.059]     at file:///vercel/path0/node_modules/.pnpm/valaxy@0.16.2_@types+markdown-it@13.0.7_@unhead+shared@1.8.9_postcss@8.4.32_typescript@5.3.3_unhead@1.8.9/node_modules/valaxy/client/.vite-ssg-temp/v0tpjfkbuq/main.mjs:5786:13
[05:01:58.059]     at renderComponentSubTree (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:427:9)
[05:01:58.059]     at renderComponentVNode (/vercel/path0/node_modules/.pnpm/@vue+server-renderer@3.4.0_vue@3.4.0/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:373:12)
[05:01:58.059]     at file:///vercel/path0/node_modules/.pnpm/vite-ssg@0.23.5_critters@0.0.20_vite@5.0.10_vue-router@4.2.5_vue@3.4.0/node_modules/vite-ssg/dist/node.mjs:1076:15
[05:01:58.059]     at async file:///vercel/path0/node_modules/.pnpm/vite-ssg@0.23.5_critters@0.0.20_vite@5.0.10_vue-router@4.2.5_vue@3.4.0/node_modules/vite-ssg/dist/node.mjs:636:36
[05:01:58.059] 
[05:01:58.059] Node.js v18.18.2
[05:01:58.136]  ELIFECYCLE  Command failed with exit code 1.
[05:01:58.155]  ELIFECYCLE  Command failed with exit code 1.
[05:01:58.169] Error: Command "pnpm run build" exited with 1
[05:01:58.626] 

### Reproduction

回退依赖版本无错误

### System Info

```Shell
win10
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MoeToo** [comment]
我也遇到了相同的问题。

**Comment by MengNianxiaoyao** [comment]
> ## 我也遇到了相同的问题。
> 似乎问题出现在valaxy-addon-meting，使用后本地构建打开为白屏；cf pages部署会报错如上。 禁用后则无错误

应该是哪个依赖出问题了，现在更新最新依赖无报错

**Comment by YunYouJun** [comment]
现在还有复现吗？

**Comment by MengNianxiaoyao** [comment]
> 现在还有复现吗？

没有
