### ISSUE TITLE
Valaxy 命令行在Ubuntu上无法运行

### ISSUE THREAD

**Issue by zsbai** [YunYouJun/valaxy#383]
### Describe the bug

本来环境在Windows上，近期迁移到WSL2的Ubuntu环境中，valaxy命令无法运行，报错如下：
```
/mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js:87
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js:96:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
      at Module._load (node:internal/modules/cjs/loader:984:27)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js:96:76)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/mnt/c/Users/baiiylu/AppData/Local/pnpm/global/5/.pnpm/rollup@4.12.1/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v20.12.2
```
在windows端可以正常执行，仅在WSL2中无法使用。
尝试通过`pnpm create valaxy`新建一个全新的仓库，相同报错无法使用命令行

### Reproduction

valaxy

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 14.39 GB / 15.43 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
安装 valaxy 时，valaxy 只安装在对应文件夹下。需要通过 `package.json` 中的命令或 `npx valaxy` 去调用。
想要全局使用就需要全局安装。
这是一个正常的表现。

推荐通过如下方式使用：

```json
{
  "name": "valaxy-blog",
  "scripts": {
    "build": "valaxy build"
  }
}
```

```bash
valaxy build
```

好处是可以和对应文件夹使用的 valaxy 版本保持一致。
全局时，则需要注意版本和本地是否一致。
