### ISSUE TITLE
升级valaxy后 build 出现错误

### ISSUE THREAD

**Issue by mcoo** [YunYouJun/valaxy#459]
### Describe the bug

从 0.19.12 升级到 0.19.13 出现
```json
  "dependencies": {
    "@css-render/vue3-ssr": "^0.15.14",
    "date-fns": "^4.1.0",
    "valaxy": "0.19.12",
    "valaxy-addon-ai-summary": "workspace:*",
    "valaxy-addon-waline": "^0.2.0",
    "valaxy-theme-yun": "0.19.12"
  },
```
1. 使用 `pnpm up --latest -i` 升级后
```
E:\projects\zh233>pnpm up --latest -i
√ Choose which packages to update (Press <space> to select, <a> to toggle all, <i> to invert selection) · naive-ui, valaxy, valaxy-theme-yun
 WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
Progress: resolved 760, reused 0, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
├─┬ valaxy 0.19.13
│ └─┬ vite-ssg 0.23.7
│   └── ✕ unmet peer critters@^0.0.20: found 0.0.24
└─┬ valaxy-addon-waline 0.2.0
  └── ✕ unmet peer valaxy@latest: found 0.19.13

Packages: +104 -86
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------
Done in 31.7s
```
2. build
```
E:\projects\zh233>pnpm build

> zh233@0.0.0 build E:\projects\zh233
> npm run build:ssg


> zh233@0.0.0 build:ssg
> valaxy build --ssg

◐ Resolve valaxy config...                                                                                                                                      17:59:33
✔ Resolve siteConfig from E:/projects/zh233/site.config.ts 53.93ms                                                                                             17:59:33
✔ Resolve userValaxyConfig from E:/projects/zh233/valaxy.config.ts 132.41ms                                                                                    17:59:33
✔ Resolve valaxy.config.ts from theme(yun) 66.96ms                                                                                                             17:59:33
✔ Resolve addons from E:/projects/zh233
  ├─ valaxy-addon-waline v0.2.0 https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-waline
  └─ valaxy-addon-ai-summary v0.0.1 (global) https://github.com/YunYouJun/valaxy

  🌌 Valaxy  v0.19.13

  🪐 theme   > yun
  📁 E:\projects\zh233

◐ Run options:resolved hooks                                                                                                                                    17:59:33  
◐ Run config:init hooks                                                                                                                                         17:59:33  
◐ Run build:before hooks                                                                                                                                        17:59:33  
ℹ Start generate fuse list...                                                                                                                                  17:59:33   
◐ Generate List for Fuse Search by (fuse.js) ...                                                                                                                17:59:33  
✔ Generate fuse list in E:\projects\zh233\public                                                                                                               17:59:34
✔ Generate fuse list in E:\projects\zh233\dist                                                                                                                 17:59:34

 ╭────────────────────────╮
 │                        │
 │  🌠 Start building...  │
 │                        │
 ╰────────────────────────╯

ℹ use vite-ssg to do ssg build...                                                                                                                              17:59:34   

[vite-ssg] Build for client...
node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunArtalk.vue?vue&type=script&setup=true&lang.ts (14:14): "useArtalkWithOptions" is not exported by "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/addons/index.ts", imported by "node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunArtalk.vue?vue&type=script&setup=true&lang.ts".
node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunTwikoo.vue?vue&type=script&setup=true&lang.ts (14:14): "useTwikooWithOptions" is not exported by "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/addons/index.ts", imported by "node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunTwikoo.vue?vue&type=script&setup=true&lang.ts".
node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunAlgoliaSearch.vue?vue&type=script&setup=true&lang.ts (20:53): "useAddonAlgolia" is not exported by "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/addons/index.ts", imported by "node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunAlgoliaSearch.vue?vue&type=script&setup=true&lang.ts".

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

[vite-ssg] Build for server...
node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunArtalk.vue?vue&type=script&setup=true&lang.ts (16:14): "useArtalkWithOptions" is not exported by "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/addons/index.ts", imported by "node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunArtalk.vue?vue&type=script&setup=true&lang.ts".
node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunTwikoo.vue?vue&type=script&setup=true&lang.ts (15:14): "useTwikooWithOptions" is not exported by "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/addons/index.ts", imported by "node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunTwikoo.vue?vue&type=script&setup=true&lang.ts".
node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunAlgoliaSearch.vue?vue&type=script&setup=true&lang.ts (22:53): "useAddonAlgolia" is not exported by "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/addons/index.ts", imported by "node_modules/.pnpm/valaxy-theme-yun@0.19.13/node_modules/valaxy-theme-yun/components/third/YunAlgoliaSearch.vue?vue&type=script&setup=true&lang.ts".
"useThemeConfig", "useValaxyDark", "useMobile", "useRouterStore", "usePostList", "useSiteConfig", "useFrontmatter", "useSidebar", "useBack", "useLocale", "useAppStore", "useValaxyConfig", "useTags", "useSiteStore", "useCategories", "useDynamicLeftSidebar", "formatDate", "usePostTitle", "sortByDate", "useInvisibleElement", "isCategoryList", "useCollections", "useDecrypt", "useRuntimeConfig", "random", "useLayout", "useFullUrl", "useBackToTop", "defineAppSetup", "initValaxyConfig", "valaxyConfigSymbol", "useActiveAnchor", "useOutline", "isEmptyAddon", "usePrevNext", "onContentUpdated", "wrapTable", "runContentUpdated", "useAplayer", "useCodePen", "useCopyCode", "useCollapseCode", "useMediumZoom", "scrollTo" and "onClickHref" are imported from external module "@valaxyjs/utils" but never used in "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/composables/outline/headers.ts" and "node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/index.ts".     
[Vue warn]: inject() can only be used inside setup() or functional components.

[vite-ssg] Rendering Pages... (52)
file:///E:/projects/zh233/node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/.vite-ssg-temp/4cegjdy6ez/main.mjs:5588
      return (_a = route.meta) == null ? void 0 : _a.layout;
                         ^

TypeError: Cannot read properties of undefined (reading 'meta')
    at ComputedRefImpl.fn (file:///E:/projects/zh233/node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/.vite-ssg-temp/4cegjdy6ez/main.mjs:5588:26)
    at refreshComputed (E:\projects\zh233\node_modules\.pnpm\@vue+reactivity@3.5.10\node_modules\@vue\reactivity\dist\reactivity.cjs.js:373:28)
    at get value [as value] (E:\projects\zh233\node_modules\.pnpm\@vue+reactivity@3.5.10\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1681:5)
    at useDynamicLeftSidebar (file:///E:/projects/zh233/node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/.vite-ssg-temp/4cegjdy6ez/main.mjs:6096:54)
    at file:///E:/projects/zh233/node_modules/.pnpm/valaxy@0.19.13_@babel+parser@7.25.6_@types+markdown-it@14.1.2_@types+node@22.7.4_async-valida_zq3hvtgajavulumm7mb6ykswe4/node_modules/valaxy/client/.vite-ssg-temp/4cegjdy6ez/main.mjs:6760:23
    at file:///E:/projects/zh233/node_modules/.pnpm/pinia@2.2.4_typescript@5.6.2_vue@3.5.10_typescript@5.6.2_/node_modules/pinia/dist/pinia.mjs:1480:98
    at EffectScope.run (E:\projects\zh233\node_modules\.pnpm\@vue+reactivity@3.5.10\node_modules\@vue\reactivity\dist\reactivity.cjs.js:81:16)
    at file:///E:/projects/zh233/node_modules/.pnpm/pinia@2.2.4_typescript@5.6.2_vue@3.5.10_typescript@5.6.2_/node_modules/pinia/dist/pinia.mjs:1480:88
    at EffectScope.run (E:\projects\zh233\node_modules\.pnpm\@vue+reactivity@3.5.10\node_modules\@vue\reactivity\dist\reactivity.cjs.js:81:16)
    at file:///E:/projects/zh233/node_modules/.pnpm/pinia@2.2.4_typescript@5.6.2_vue@3.5.10_typescript@5.6.2_/node_modules/pinia/dist/pinia.mjs:1480:54

Node.js v20.17.0
 ELIFECYCLE  Command failed with exit code 1.
```
3. 清理`node_modules`与`pnpm-lock.yaml`后重新`pnpm i` 可以编译通过

[lock对比.zip](https://github.com/user-attachments/files/17203419/lock.zip)

### Reproduction

N/A

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.12 GB / 15.84 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mcoo** [comment]
vue 版本问题，在 `package.json` 中添加
```
  "resolutions": {
    "vue": "^3.5.10"
  }
```
非共性问题
